name: Generate TWRP Device Tree

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'Library name for the device tree'
        required: true
        default: 'Twrp_Device_Generator'
      IMG_URL:
        description: 'URL to recovery/boot image'
        required: true
        default: 'https://github.com/resparkstar/action_build_twrp_device_tree/raw/main/recovery.img'

jobs:
  generate-device-tree:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install wget 
        
      
    - name: Download recovery image
      run: |
        wget -O recovery.img "${{ github.event.inputs.IMG_URL }}"
       
   
