name: huanjing

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          mkdir ~/bin
          mkdir -p ~/android/lineage
          cd ~/android/lineage

