name: Android NDK Build
on:   
   workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27d
          link-to-sdk: true

      - name: Verify NDK Path
        run: |
         sudo apt update
         sudo apt -y install wget
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          ls -la $ANDROID_NDK_HOME
          wget -P $ANDROID_NDK_HOME https://github.com/resparkstar/you-get-test/blob/main/Application.mk
          wget -P $ANDROID_NDK_HOME https://github.com/kangtastic/cve-2019-2215/blob/master/cve-2019-2215.c
          cd  $ANDROID_NDK_HOME
          ls 
          
          
          
