name: Android NDK Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27d
          link-to-sdk: true

      - name: Verify NDK Path
        run: |
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          ls -la $ANDROID_NDK_HOME
          cd  $ANDROID_NDK_HOME
          ls 
        
          
          
          
